"""The brick catalog (docs/loupe-scaffold.md §4's "Initial brick catalog",
§6 build-order steps 3-4).

Per §6's own sequencing: build `core_app` plus exactly one full path first
(PostgreSQL + async SQLAlchemy + JWT + docker-compose + basic testing —
the §5 end-to-end acceptance combination), get that proven end-to-end, only
then expand outward. What's here beyond that one proven path is a
deliberately modest set — one simple alternative per elicitation question
(`db_sqlite`, `auth_none`, `background_none`, `deploy_bare`, `testing_ci`)
so the compose mechanism is demonstrated to generalize, not a claim of full
240-combination coverage (§2 explicitly scopes broad coverage as the
end-state, not a day-one requirement).

Known, deliberate gap: `db_postgresql`'s `docker-compose.yml` contribution
(a `db:` service block) is only valid when `deploy_docker_compose` is also
selected — it assumes something else already opened the file's top-level
`services:` key. Selecting PostgreSQL with a non-docker-compose deployment
target produces no `docker-compose.yml` at all, so this never actually
misfires today, but it's a real coupling between two nominally-independent
bricks worth naming rather than leaving implicit.
"""

from __future__ import annotations

from loupe_core.adapters.fastapi.convention_categories import ConventionCategory

from .compose import Brick

# --------------------------------------------------------------------------
# core_app — always included (§4's catalog: "main.py skeleton, config.py
# base, structured logging, Dockerfile, README generator"). README
# generation is deliberately not a brick — see generate.py.
# --------------------------------------------------------------------------

_GITIGNORE = """\
__pycache__/
*.pyc
.venv/
venv/
.env
*.db
.pytest_cache/
"""

_DOCKERFILE = """\
FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir .

COPY app ./app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
"""

_MAIN_PY_HEADER = '''\
"""{{ one_line_purpose }}"""

import logging

from fastapi import FastAPI

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="{{ project_name }}")


@app.get("/health")
def health_check() -> dict:
    return {"status": "ok"}
'''

_CONFIG_PY_HEADER = '''\
from functools import lru_cache

from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    app_name: str = "{{ project_name }}"
    debug: bool = False
'''

CORE_APP = Brick(
    name="core_app",
    exclusive_files={
        "app/__init__.py": "",
        "tests/__init__.py": "",
        ".gitignore": _GITIGNORE,
        "Dockerfile": _DOCKERFILE,
    },
    shared_contributions={"app/main.py": _MAIN_PY_HEADER, "app/config.py": _CONFIG_PY_HEADER},
    shared_bases=frozenset({"app/main.py", "app/config.py"}),
    dependencies=["fastapi>=0.115", "uvicorn[standard]>=0.30", "pydantic-settings>=2.4"],
    env_vars={"APP_NAME": "{{ project_name }}", "DEBUG": "false"},
    category=ConventionCategory.CONFIG_MANAGEMENT,
)


# --------------------------------------------------------------------------
# Database
# --------------------------------------------------------------------------

DB_POSTGRESQL = Brick(
    name="db_postgresql",
    shared_contributions={
        "app/config.py": '    database_url: str = "postgresql+asyncpg://app:app@db:5432/app"\n',
        "docker-compose.yml": (
            "  db:\n"
            "    image: postgres:16\n"
            "    environment:\n"
            "      POSTGRES_USER: app\n"
            "      POSTGRES_PASSWORD: app\n"
            "      POSTGRES_DB: app\n"
            '    ports:\n      - "5432:5432"\n'
        ),
    },
    env_vars={"DATABASE_URL": "postgresql+asyncpg://app:app@db:5432/app"},
    category=ConventionCategory.CONFIG_MANAGEMENT,
)

DB_SQLITE = Brick(
    name="db_sqlite",
    shared_contributions={"app/config.py": '    database_url: str = "sqlite+aiosqlite:///./app.db"\n'},
    dependencies=["aiosqlite>=0.20"],
    env_vars={"DATABASE_URL": "sqlite+aiosqlite:///./app.db"},
    category=ConventionCategory.CONFIG_MANAGEMENT,
)


# --------------------------------------------------------------------------
# ORM
# --------------------------------------------------------------------------

_DATABASE_PY = '''\
"""Async SQLAlchemy engine/session setup (generated by loupe new)."""

from collections.abc import AsyncGenerator

from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.config import get_settings

settings = get_settings()

engine = create_async_engine(settings.database_url)
async_session_factory = async_sessionmaker(engine, expire_on_commit=False)


async def get_session() -> AsyncGenerator[AsyncSession, None]:
    async with async_session_factory() as session:
        yield session
'''

ORM_SQLALCHEMY_ASYNC = Brick(
    name="orm_sqlalchemy_async",
    exclusive_files={"app/database.py": _DATABASE_PY},
    dependencies=["sqlalchemy[asyncio]>=2.0", "asyncpg>=0.29"],
    category=ConventionCategory.DEPENDENCY_INJECTION,
)


# --------------------------------------------------------------------------
# Migrations
# --------------------------------------------------------------------------

_ALEMBIC_INI = """\
[alembic]
script_location = alembic
sqlalchemy.url = driver://user:pass@localhost/dbname
"""

_ALEMBIC_ENV_PY = '''\
"""Alembic environment (generated by loupe new — fill in target_metadata once models exist)."""

from alembic import context

config = context.config
target_metadata = None


def run_migrations_offline() -> None:
    context.configure(url=config.get_main_option("sqlalchemy.url"), target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
'''

MIGRATIONS_ALEMBIC = Brick(
    name="migrations_alembic",
    exclusive_files={
        "alembic.ini": _ALEMBIC_INI,
        "alembic/env.py": _ALEMBIC_ENV_PY,
        "alembic/versions/.gitkeep": "",
    },
    dependencies=["alembic>=1.13"],
)


# --------------------------------------------------------------------------
# Auth
# --------------------------------------------------------------------------

AUTH_NONE = Brick(name="auth_none")

_AUTH_ROUTES_PY = '''\
"""JWT-based authentication routes (generated by loupe new) — replace the
placeholder credential check with real user lookup before shipping."""

from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, HTTPException
from jose import jwt
from pydantic import BaseModel

from app.config import get_settings

router = APIRouter(prefix="/auth", tags=["auth"])


class TokenRequest(BaseModel):
    username: str
    password: str


class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"


@router.post("/token", response_model=TokenResponse)
def issue_token(payload: TokenRequest) -> TokenResponse:
    if not payload.username or not payload.password:
        raise HTTPException(status_code=401, detail="invalid credentials")

    settings = get_settings()
    expire = datetime.now(timezone.utc) + timedelta(hours=1)
    token = jwt.encode(
        {"sub": payload.username, "exp": expire},
        settings.jwt_secret_key,
        algorithm=settings.jwt_algorithm,
    )
    return TokenResponse(access_token=token)
'''

_AUTH_SECURITY_PY = '''\
"""Reusable `Depends(get_current_username)` dependency for protected routes
(generated by loupe new)."""

from fastapi import Depends, HTTPException
from fastapi.security import OAuth2PasswordBearer
from jose import JWTError, jwt

from app.config import get_settings

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/token")


def get_current_username(token: str = Depends(oauth2_scheme)) -> str:
    settings = get_settings()
    try:
        payload = jwt.decode(token, settings.jwt_secret_key, algorithms=[settings.jwt_algorithm])
    except JWTError:
        raise HTTPException(status_code=401, detail="invalid token") from None
    username = payload.get("sub")
    if username is None:
        raise HTTPException(status_code=401, detail="invalid token")
    return username
'''

AUTH_JWT = Brick(
    name="auth_jwt",
    exclusive_files={
        "app/auth/__init__.py": "",
        "app/auth/routes.py": _AUTH_ROUTES_PY,
        "app/auth/security.py": _AUTH_SECURITY_PY,
    },
    shared_contributions={
        "app/main.py": "\nfrom app.auth.routes import router as auth_router\n\napp.include_router(auth_router)\n",
        "app/config.py": '    jwt_secret_key: str = "change-me"\n    jwt_algorithm: str = "HS256"\n',
    },
    dependencies=["python-jose[cryptography]>=3.3", "passlib[bcrypt]>=1.7", "python-multipart>=0.0.9"],
    env_vars={"JWT_SECRET_KEY": "change-me", "JWT_ALGORITHM": "HS256"},
    category=ConventionCategory.DEPENDENCY_INJECTION,
)


# --------------------------------------------------------------------------
# Background work
# --------------------------------------------------------------------------

BACKGROUND_NONE = Brick(name="background_none")


# --------------------------------------------------------------------------
# Deployment
# --------------------------------------------------------------------------

DEPLOY_DOCKER_COMPOSE = Brick(
    name="deploy_docker_compose",
    shared_contributions={
        "docker-compose.yml": 'services:\n  app:\n    build: .\n    ports:\n      - "8000:80"\n    env_file:\n      - .env\n'
    },
    shared_bases=frozenset({"docker-compose.yml"}),
)

DEPLOY_BARE = Brick(name="deploy_bare")


# --------------------------------------------------------------------------
# Observability
# --------------------------------------------------------------------------

OBSERVABILITY_MINIMAL = Brick(name="observability_minimal")


# --------------------------------------------------------------------------
# Testing
# --------------------------------------------------------------------------

_TEST_HEALTH_PY = '''\
from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_health_check_returns_ok():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}
'''

TESTING_BASIC = Brick(
    name="testing_basic",
    exclusive_files={"tests/test_health.py": _TEST_HEALTH_PY},
    dependencies=["pytest>=8.0", "httpx>=0.27"],
)

_CI_WORKFLOW_YML = """\
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e ".[dev]"
      - run: pytest
"""

TESTING_CI = Brick(
    name="testing_ci",
    exclusive_files={
        "tests/test_health.py": _TEST_HEALTH_PY,
        ".github/workflows/ci.yml": _CI_WORKFLOW_YML,
    },
    dependencies=["pytest>=8.0", "httpx>=0.27"],
)


BRICK_REGISTRY: dict[str, Brick] = {
    brick.name: brick
    for brick in [
        CORE_APP,
        DB_POSTGRESQL,
        DB_SQLITE,
        ORM_SQLALCHEMY_ASYNC,
        MIGRATIONS_ALEMBIC,
        AUTH_NONE,
        AUTH_JWT,
        BACKGROUND_NONE,
        DEPLOY_DOCKER_COMPOSE,
        DEPLOY_BARE,
        OBSERVABILITY_MINIMAL,
        TESTING_BASIC,
        TESTING_CI,
    ]
}
