"""Ties elicitation -> brick selection -> compose -> manifest/README generation
together and writes the result to disk (docs/loupe-scaffold.md §4 steps 7-8,
§6 build-order steps 3 and 5).

Manifest/`.loupeignore` generation (step 7) and README generation (step 8)
are deliberately *not* bricks, matching `compose.py`'s own module docstring
— every new project gets exactly one manifest/ignore-file pair regardless
of stack, and the README has to describe whatever the *actual* activated
brick set turned out to be, which isn't knowable until after compose runs.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from .bricks import BRICK_REGISTRY
from .compose import Brick, compose, select_bricks
from .elicitation import run_elicitation

# Loupe's own manifest schema (docs/loupe-target-project-standard.md §3) —
# duplicated as a small literal template rather than imported from
# `loupe_mcp_server`: Scaffold stays CLI-only and never touches the MCP
# server (docs/loupe-scaffold.md §2's explicit scope), and importing that
# package here would drag in its full retrieval/embedding dependency chain
# for the sake of one integer constant.
_LOUPE_MANIFEST_SCHEMA_VERSION = 1

_LOUPEIGNORE = """\
__pycache__/
.venv/
venv/
node_modules/
dist/
build/
"""

# §3's fixed core questions that don't map to a brick-selection field at all
# (free text, used only for doc/context purposes).
_NON_BRICK_QUESTION_IDS = {"project_name", "one_line_purpose"}


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.strip().lower()).strip("-")
    return slug or "generated-app"


def build_context(answers: dict[str, Any]) -> dict[str, Any]:
    """Elicitation answers, plus derived values every brick template may need."""
    context = dict(answers)
    context.setdefault("project_name", "Generated App")
    context.setdefault("one_line_purpose", "")
    context["package_name"] = _slugify(context["project_name"])
    return context


def generate_manifest(languages: list[str] | None = None) -> str:
    langs = ", ".join(languages or ["python"])
    return (
        "# loupe.manifest.yaml\n"
        f"schema_version: {_LOUPE_MANIFEST_SCHEMA_VERSION}\n\n"
        f"languages:\n  - {langs}\n\n"
        "token_budget:\n  default_per_turn: 6000\n  hard_ceiling: 20000\n\n"
        "compute_profile: cpu_small\n"
        "embedding_model: auto\n"
        "cross_encoder_model: auto\n\n"
        "index:\n  symbol_kinds: [function, class, method]\n  exclude_paths: []\n"
    )


_STACK_LABELS: dict[str, str] = {
    "db_postgresql": "PostgreSQL",
    "db_sqlite": "SQLite",
    "db_mysql": "MySQL",
    "db_mongodb": "MongoDB",
    "orm_sqlalchemy_async": "async SQLAlchemy",
    "orm_sqlalchemy_sync": "sync SQLAlchemy",
    "orm_sqlmodel": "SQLModel",
    "orm_beanie": "Beanie",
    "migrations_alembic": "Alembic migrations",
    "auth_jwt": "JWT authentication",
    "auth_api_key": "API key authentication",
    "auth_oauth2_social": "OAuth2 social login",
    "auth_session": "session-based authentication",
    "background_simple_tasks": "simple background tasks",
    "background_celery_redis": "Celery with Redis for background work",
    "background_celery_rabbitmq": "Celery with RabbitMQ for background work",
    "background_arq": "arq for background work",
    "deploy_docker_compose": "Docker Compose",
    "deploy_kubernetes": "Kubernetes",
    "deploy_serverless_lambda": "serverless (AWS Lambda)",
    "deploy_bare": "bare uvicorn",
    "observability_structured_logging": "structured logging",
    "observability_otel": "OpenTelemetry",
    "testing_ci": "CI-integrated tests",
}


def generate_readme(context: dict[str, Any], bricks: list[Brick]) -> str:
    """§4 step 8: name the real chosen stack, don't mention what wasn't
    selected — every label below is only present because a real activated
    brick put it there, not templated around the answers.
    """
    brick_names = {b.name for b in bricks}
    stack_bullets = [_STACK_LABELS[name] for name in sorted(brick_names) if name in _STACK_LABELS]

    lines = [f"# {context['project_name']}", ""]
    if context.get("one_line_purpose"):
        lines += [context["one_line_purpose"], ""]
    lines += ["Generated by `loupe new`.", ""]
    lines += ["## Stack", ""]
    if stack_bullets:
        lines += [f"- {label}" for label in stack_bullets]
    else:
        lines += ["- FastAPI (no database, auth, or background work selected)"]
    lines += [
        "",
        "## Run it",
        "",
        "```bash",
        "pip install -e \".[dev]\"",
        "cp .env.example .env",
        "uvicorn app.main:app --reload",
        "```",
        "",
    ]
    return "\n".join(lines)


def generate_project_files(answers: dict[str, Any]) -> dict[str, str]:
    """The full pipeline (§4 steps 1-8) minus disk I/O — returns `{path: content}`
    for every file the generated project should have. Split from
    `write_project` so tests can inspect output without touching a filesystem.
    """
    context = build_context(answers)
    bricks = select_bricks(answers, BRICK_REGISTRY)

    files = compose(bricks, context)
    files["loupe.manifest.yaml"] = generate_manifest()
    files[".loupeignore"] = _LOUPEIGNORE
    files["README.md"] = generate_readme(context, bricks)
    return files


def write_project(output_dir: Path, answers: dict[str, Any]) -> None:
    files = generate_project_files(answers)
    for rel_path, content in files.items():
        full_path = output_dir / rel_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content)


def run_and_write(output_dir: Path, answer_fn) -> dict[str, Any]:
    """CLI-facing entrypoint: run the elicitation interview, then generate
    and write the project. Returns the collected answers (useful for the
    CLI to print a summary)."""
    answers = run_elicitation(answer_fn)
    write_project(output_dir, answers)
    return answers
